### PR TITLE
Adopt chat-extension-utils

### PR DESCRIPTION
**Pull request by roblourens**
What do you think?

@amunger @eleanorjboyd @joshspicer 

I think the big string prompt is a bit ugly, I'm thinking about supporting PromptElements for that.

### CODE REVIEW

**Comment by amunger** [comment]
It's much harder to tell how tools will be used and how they are used in the prompt. I assume they just get run and the result is inserted into the prompt, but maybe harder to troubleshoot or adjust. Definitely nicer that I don't need to worry about caching tool results though - that part felt like the most obvious part that everyone would need.

LGTM overall.

**Review by roblourens — COMMENTED** [review]
Yeah, but the idea is that you shouldn't _have_ to do much troubleshooting, the library should do the right thing. Is there something that you expect having to adjust?

You do bring up a good point that it should give you a way to see the real prompt/request, maybe starting up the trace utility.

**Comment by amunger** [comment]
Yeah I think I would just want that visibility to confirm that it is getting the context correctly.

**Comment by roblourens** [comment]
I did add something to show the trace utility, it prints a message inline. I also opened this https://github.com/microsoft/vscode-prompt-tsx/issues/134

**Comment by roblourens** [comment]
Any other thoughts on this? It doesn't have to be merged, but it would be cool if it was

**Review by karthiknadig — APPROVED** [review]

**Comment by roblourens** [comment]
Looks like this was depending on a version of the library that wasn't published yet- I'll fix that up. I am a little scared that you were willing to merge it without trying it but I appreciate your trust! 😄

**Comment by eleanorjboyd** [comment]
will try it next time haha

**Pull request merged**
